# Generated by Django 3.1.7 on 2021-05-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
