# Generated by Django 3.1.7 on 2021-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='username',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
